stages:
  - test

.test-gpg-script: &test-gpg
  stage: test
  script:
    - ./corelight-gpg.sh

centos6_test:
  image: centos:6
  <<: [*test-deb]

centos7_test:
  image: centos:7
  <<: [*test-deb]

centos8_test:
  image: centos:8
  <<: [*test-deb]

rhel7_test:
  image: registry.access.redhat.com/ubi7/ubi
  <<: [*test-deb]

rhel8_test:
  image: registry.access.redhat.com/ubi8/ubi
  <<: [*test-deb]

debian_buster_test:
  image: debian:10
  <<: [*test-deb]

debian_bullseye_test:
  image: debian:11
  <<: [*test-deb]

# docker image for debian:12 is not available
# debian_bookworm_test:
#   stage: test
#   image: debian:12
#   script:
#     - ./corelight-gpg.sh

# docker image for debian:13 is not available
# debian_trixie_test:
#   stage: test
#   image: debian:13
#   script:
#     - ./corelight-gpg.sh

# docker image for raspbian:buster is not available
# raspbian_buster_test:
#   stage: test
#   image: raspbian:buster
#   script:
#     - ./corelight-gpg.sh

# docker image for raspbian:bullseye is not available
# raspbian_bullseye_test:
#   stage: test
#   image: raspbian:bullseye
#   script:
#     - ./corelight-gpg.sh

ubuntu_bionic_test:
  image: ubuntu:18.04
  <<: [*test-deb]

ubuntu_focal_test:
  image: ubuntu:20.04
  <<: [*test-deb]

ubuntu_hirsute_test:
  image: ubuntu:21.04
  <<: [*test-deb]

ubuntu_impish_test:
  image: ubuntu:21.10
  <<: [*test-deb]

ubuntu_jammy_test:
  image: ubuntu:22.04
  <<: [*test-deb]

amazon_linux2_test:
  image: amazonlinux:2
  <<: [*test-deb]
